### ISSUE TITLE
I am getting ERROR: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Amritmatti** [moayyadfaris/opsworks_cookbook#1]
================================================================================
Recipe Compile Error in /var/chef/runs/4443b430-dc67-45e1-a301-edce9819902e/local-mode-cache/cache/cookbooks/OpsWorks/recipes/default.rb
================================================================================
 
NoMethodError
-------------
undefined method `[]' for nil:NilClass
 
Cookbook Trace:
---------------
/var/chef/runs/4443b430-dc67-45e1-a301-edce9819902e/local-mode-cache/cache/cookbooks/OpsWorks/recipes/default.rb:12:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/4443b430-dc67-45e1-a301-edce9819902e/local-mode-cache/cache/cookbooks/OpsWorks/recipes/default.rb:
 
5:  # Copyright:: 2018, Moayyad Faris, All Rights Reserved.
6:  
7:  execute "update-upgrade" do
8:    command "sudo apt-get update && sudo apt-get upgrade -y"
9:    action :run
10:  end
11:  
12>> release_user = node[:deployer]["name"]
13:  release_group = node[:deployer]["group"]
14:  group release_group
15:  home = "/home/#{release_user}"
16:  
17:  user release_user do
18:        action :create
19:        comment "deploy user"
20:        gid release_group
21:        home home
 
Platform:
---------
x86_64-linux
 
[2021-07-22T13:20:21+00:00] ERROR: Running exception handlers
[2021-07-22T13:20:21+00:00] ERROR: Exception handlers complete
[2021-07-22T13:20:21+00:00] FATAL: Stacktrace dumped to /var/chef/runs/4443b430-dc67-45e1-a301-edce9819902e/local-mode-cache/cache/chef-stacktrace.out
[2021-07-22T13:20:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-07-22T13:20:21+00:00] ERROR: undefined method `[]' for nil:NilClass
[2021-07-22T13:20:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by fcenteno** [comment]
I have the same error too

**Comment by kapilAPS** [comment]
seems these recipes are not up to date. These are too old

**Comment by Amritmatti** [comment]
seems these recipes are not up to date

**Comment by kapilAPS** [comment]
for haproxy
 
================================================================================
Recipe Compile Error in /var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb
================================================================================
 
NoMethodError
-------------
undefined method `+' for nil:NilClass
 
Cookbook Trace:
---------------
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:69:in `block in from_file'
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:39:in `each'
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:39:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:
 
62:      only_if do
63:        app[:enable_ssl] && app[:ssl_configuration][:chain]
64:      end
65:    end
66:  
67:    Chef::Log.info("debugging haproxy recipe...")
68:  
69>>   ssl_pem = app[:ssl_configuration][:private_key] + "\n" + app[:ssl_configuration][:certificate] + "\n" + app[:ssl_configuration][:chain]
70:  
71:    template "#{node[:haproxy][:dir]}/ssl/#{node[:haproxy][:cert]}.pem" do
72:      mode 0600
73:      source 'haproxy/ssl.key.erb'
74:      variables :key => ssl_pem
75:      only_if do
76:        app[:enable_ssl] && app[:ssl_configuration][:certificate] && app[:ssl_configuration][:private_key] && app[:ssl_configuration][:chain]
77:      end
78:    end
 
Platform:
---------
x86_64-linux
 
[2021-07-23T11:36:53+00:00] ERROR: Running exception handlers
[2021-07-23T11:36:53+00:00] ERROR: Exception handlers complete
[2021-07-23T11:36:53+00:00] FATAL: Stacktrace dumped to /var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/chef-stacktrace.out
[2021-07-23T11:36:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-07-23T11:36:53+00:00] ERROR: undefined method `+' for nil:NilClass
[2021-07-23T11:36:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by Amritmatti** [comment]
For haproxy



================================================================================
Recipe Compile Error in /var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb
================================================================================
 
NoMethodError
-------------
undefined method `+' for nil:NilClass
 
Cookbook Trace:
---------------
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:69:in `block in from_file'
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:39:in `each'
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:39:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/cookbooks/OpsWorks/recipes/haproxy.rb:
 
62:      only_if do
63:        app[:enable_ssl] && app[:ssl_configuration][:chain]
64:      end
65:    end
66:  
67:    Chef::Log.info("debugging haproxy recipe...")
68:  
69>>   ssl_pem = app[:ssl_configuration][:private_key] + "\n" + app[:ssl_configuration][:certificate] + "\n" + app[:ssl_configuration][:chain]
70:  
71:    template "#{node[:haproxy][:dir]}/ssl/#{node[:haproxy][:cert]}.pem" do
72:      mode 0600
73:      source 'haproxy/ssl.key.erb'
74:      variables :key => ssl_pem
75:      only_if do
76:        app[:enable_ssl] && app[:ssl_configuration][:certificate] && app[:ssl_configuration][:private_key] && app[:ssl_configuration][:chain]
77:      end
78:    end
 
Platform:
---------
x86_64-linux
 
[2021-07-23T11:36:53+00:00] ERROR: Running exception handlers
[2021-07-23T11:36:53+00:00] ERROR: Exception handlers complete
[2021-07-23T11:36:53+00:00] FATAL: Stacktrace dumped to /var/chef/runs/65a4a4a8-86a2-4302-adce-9af29b12e49b/local-mode-cache/cache/chef-stacktrace.out
[2021-07-23T11:36:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-07-23T11:36:53+00:00] ERROR: undefined method `+' for nil:NilClass
[2021-07-23T11:36:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
